import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeContextProvider } from "@/context/Themecontext";
import ThemeProvider from "@/providers/ThemeProvider";
import {AuthProvider} from "@/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50 dark:bg-gray-900`}>
        <ThemeContextProvider>
          <ThemeProvider>
            <AuthProvider>
              <div className="container1 dark:bg-slate-950 dark:text-white h-full ">
                <div className="wrapper">{children}</div>
              </div>
            </AuthProvider>
          </ThemeProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
